### ISSUE TITLE
Add CUDAnativelib to buildbot

### ISSUE THREAD

**Issue by vchuravy** [maleadt/julia-buildbot#1]
Cxx.jl got tagged for Julia v0.6- and I want to tag and release a version of CUDAnativelib, having CI for that would be great.

**Comment by maleadt** [comment]
Hmm, I guess Cxx.jl's build doesn't like me tarballing `usr`...
https://ci.maleadt.net/buildbot/julia/builders/CUDAnativelib.jl%3A%20Julia%20master%20%28x86-64%29/builds/113/steps/build/logs/stdio

**Comment by maleadt** [comment]
Let's just start with https://github.com/maleadt/julia-buildbot/commit/1cac2a6d53f2f22063d993f76b52c3df8fb6219d

**Comment by vchuravy** [comment]
That's a good start :)

**Comment by maleadt** [comment]
I won't have time soon to fix this, maybe you could have a look? We now have Julia builds with Clang enabled, ~~see eg. [this build artefact](http://users.elis.ugent.be/~tbesard/public/julia-0.6.0-dev.2921.tar)~~ (that won't work because sys.so is hw dep), but because `llvm-config` exists Cxx.jl [gets tricked](https://github.com/Keno/Cxx.jl/blob/2fe24c9048e60f61f7b93061e1b82f8e0495b0d6/deps/build.jl#L43) into thinking we're doing a source build, making it try to [include `Versions.make`](https://github.com/Keno/Cxx.jl/blob/2fe24c9048e60f61f7b93061e1b82f8e0495b0d6/deps/BuildBootstrap.Makefile#L6). That fails.

**Comment by maleadt** [comment]
This got me building Cxx.jl:
```patch
diff --git a/deps/build.jl b/deps/build.jl
index 81f6335..8cb78b8 100644
--- a/deps/build.jl
+++ b/deps/build.jl
@@ -44,11 +44,16 @@ llvm_config_path = joinpath(BASE_JULIA_BIN,"..","tools","llvm-config")
 if isfile(llvm_config_path)
     info("Building julia source build")
     ENV["LLVM_CONFIG"] = llvm_config_path
-    delete!(ENV,"LLVM_VER")
+    ENV["LLVM_VER"] = readchomp(`$llvm_config_path --version`)
+
+    clang_path = joinpath(BASE_JULIA_BIN,"..","tools","clang")
+    ENV["BUILD_LLVM_CLANG"] = isfile(clang_path) ? "1" : "0"
 else
     info("Building julia binary build")
     ENV["LLVM_VER"] = Base.libllvm_version
     ENV["JULIA_BINARY_BUILD"] = "1"
     ENV["PATH"] = string(JULIA_HOME,":",ENV["PATH"])
 end
```

before I realised Cxx.jl's dep uses private Clang headers and we hence _need_ to have access to the entire build tree...

**Comment by maleadt** [comment]
Okay, see https://github.com/maleadt/julia-buildbot/commit/5b0ed30090ec9859d2b5d4700a4a4abfd22525f7, I've now included more parts of the build tree (all of `usr`, `Make.user`, `deps/Versions.make` and the LLVM sources) in order to support Cxx.jl. That seems to work: https://ci.maleadt.net/buildbot/julia/builders/CUDAnativelib.jl%3A%20Julia%20master%20%28x86-64%29/builds/123/steps/resolve/logs/stdio

CUDAnativelib.jl doesn't work though; https://ci.maleadt.net/buildbot/julia/builders/CUDAnativelib.jl%3A%20Julia%20master%20%28x86-64%29/builds/123/steps/test/logs/stdio
Could you extend the defaults instead? The buildbot runs on a vanilla Debian system, with `cuda.h` in `/usr/include`. You also might want to do this in a build step.

I'll activate the webhook for building CUDAnativelib.jl. There's also a trigger build, where changes to julia trigger a build of the current master branch, so you might want to monitor https://ci.maleadt.net/buildbot/julia/waterfall?tag=CUDAnativelib or include build badges to the README (see CUDAnative.jl's README).

**Comment by vchuravy** [comment]
Perfect that works! Thanks :)
